replicaCount: 2

image:
  repository: ghcr.io/rpmwin/devops-platform-sample-app
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "traefik"
  host: sample-app.local

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

serviceAccount:
  create: true
  name: "sample-app"

livenessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 3
  periodSeconds: 5

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"
