---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-app-secret
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgBpC8C0lcBbs5uGkRYWqjpwTF0rxa4iIL/4aQkoYkpytGsAs99XC9dzmNim9rCyFqGy3x4+un6YtgHRqsTT4MDbVOkjzu567dSGjD/u0/nuPesA7rqMG5RwnxE68TF/AlAfDJVwlkgRwErZRC7oIuNXnRZ5h1/YBgKUUVK1TBAoXLzgj14LtFRMJYTtsWTYQFEQw+ku/EokdNKOzs6lne3sCf7Fqw3xLIVkAS34fUDnbLkI3XrGoX5DHecX42ZCH6HgexnwGes0oz+dAUccbKkvqTEZV23jfwlvZ1LryElh6ZvcRx0CKOD1BIetUh0xQZckA+D07D5rrFL0O5Rloy1rWn6dAKE22KJc8wvBeHqBpbx5FWPCm5S6nMr4HJDf4KYqwjazU4L+Apf7TJEVCWCbFhRBw1bH7Dje4COFnlryQNU/sjvLwwKTah780cDtbZUDcoRJO9XHef3Oc4gXkr+YuU7tVDgwdEwikgdwnWyflxPj6ihluyG5JPWyNQCttmSNkjzy1fM2oJ/e8W3htgy5dhfsz24jwiSg8kP/0z0duZaurIJ/DrRd7gn+RtVLdJl1uov0fgOb3Mk348iN/WKL8M+Lppd3n0s1zPP+JYdIMoJUuORYuxg2iYgJKxB3ISHrwFb93DJr6w1w4H5jbasi42QtfIDl6iP1wqUpTn5LUToZ8mpdgTQW7tnd7QNjd/3QKKCZisABoeF25p+hg64k0e3PaI0Iu2QdAsPuBbcYyPRXnazPjdYxBV8qkqaM
  template:
    metadata:
      name: sample-app-secret
      namespace: apps
    type: Opaque
